name: Deploy Polygon Listener

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define Docker image tag
        id: tags
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/onchain-event-listener"
          LATEST_TAG="${IMAGE_NAME}:latest"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image using Dockerfile
        run: docker build -t ${{ env.LATEST_TAG }} .

      - name: Push Docker image
        run: docker push ${{ env.LATEST_TAG }}
