name: Deploy Onchain Listener

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "production"
        type: choice
        options:
          - develop
          - certification
          - production

jobs:
  build-and-push:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define Docker image tag
        id: tags
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/onchain-event-listener"
          TAG="${{ github.event.inputs.environment }}-latest"
          IMAGE_TAG="${IMAGE_NAME}:${TAG}"

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "ðŸ§© Using image tag: $IMAGE_TAG"

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_TAG }}
